// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace RegulatedNoise.DomainModel
{
    public struct WarningLevels
    {
        [JsonProperty("sell")] 
        public readonly PriceBounds Sell;

        [JsonProperty("buy")] 
        public readonly PriceBounds Buy;

        public WarningLevels(int sell_low = -1, int sell_high = -1, int buy_low = -1, int buy_high = -1)
        {
            Sell = new PriceBounds(sell_low, sell_high);
            Buy = new PriceBounds(buy_low, buy_high);
        }
    }

    public struct PriceBounds
    {
        [JsonProperty("low")] 
        public readonly int Low;

        [JsonProperty("high")] 
        public readonly int High;

        public PriceBounds(int low = -1, int high = -1)
        {
            Low = low;
            High = high;
        }
    }
}
