// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace RegulatedNoise.Core.DomainModel
{
    public enum UpdateMode
    {
        /// <summary>
        /// copy values but not id
        /// </summary>
        Copy,
        /// <summary>
        /// copy everything
        /// </summary>
        Clone,
        /// <summary>
        /// set only values which are not set or newer
        /// </summary>
        Update
    }
}
