// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace RegulatedNoise.EDDN
{

    /// <summary>
    /// schema class,
    /// based on the structure from 
    /// https://github.com/jamesremuscat/EDDN/blob/master/schemas/commodity-v2.0.json
    /// </summary>
    internal partial class Schema_v2
    {
        internal class Header_Class
        {

            [JsonProperty("softwareVersion")]
            public string SoftwareVersion { get; set; }

            [JsonProperty("gatewayTimestamp")]
            public string GatewayTimestamp { get; set; }

            [JsonProperty("softwareName")]
            public string SoftwareName { get; set; }

            [JsonProperty("uploaderID")]
            public string UploaderID { get; set; }
        }
    }

    internal partial class Schema_v2
    {
        internal class Commodity_Class
        {

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("buyPrice")]
            public int BuyPrice { get; set; }

            [JsonProperty("supplyLevel")]
            public string SupplyLevel { get; set; }

            [JsonProperty("supply")]
            public int Supply { get; set; }

            [JsonProperty("demand")]
            public int Demand { get; set; }

            [JsonProperty("sellPrice")]
            public int SellPrice { get; set; }

            [JsonProperty("demandLevel")]
            public string DemandLevel { get; set; }
        }
    }

    internal partial class Schema_v2
    {
        internal class Message_Class
        {

            [JsonProperty("commodities")]
            public Commodity_Class[] Commodities { get; set; }

            [JsonProperty("timestamp")]
            public string Timestamp { get; set; }

            [JsonProperty("systemName")]
            public string SystemName { get; set; }

            [JsonProperty("stationName")]
            public string StationName { get; set; }
        }
    }

    internal partial class Schema_v2
    {

        [JsonProperty("header")]
        public Header_Class Header { get; set; }

        [JsonProperty("$schemaRef")]
        public string SchemaRef { get; set; }

        [JsonProperty("message")]
        public Message_Class Message { get; set; }
    }

}
