// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace RegulatedNoise.EDDB_Data
{

    public class Listing
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("station_id")]
        public int StationId { get; set; }

        [JsonProperty("commodity_id")]
        public int CommodityId { get; set; }

        [JsonProperty("supply")]
        public int Supply { get; set; }

        [JsonProperty("buy_price")]
        public int BuyPrice { get; set; }

        [JsonProperty("sell_price")]
        public int SellPrice { get; set; }

        [JsonProperty("demand")]
        public int Demand { get; set; }

        [JsonProperty("collected_at")]
        public int CollectedAt { get; set; }

        [JsonProperty("update_count")]
        public int UpdateCount { get; set; }
    }

}
